name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'
          extended: true
      
      - name: Import BibTeX
        run: pip3 install --upgrade setuptools && pip3 install academic && academic import --overwrite --normalize --bibtex publications.bib

      - name: Build
        run: hugo --gc --minify -b https://www.ieap.uni-kiel.de/et/people/forstner

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public